protected/models/Task.php
<?php

/**
 * This is the model class for table "task".
 *
 * The followings are the available columns in table 'task':
 * @property integer $task_id
 * @property integer $company_id
 * @property integer $employee_id
 * @property integer $user_id
 * @property integer $task_frequency_id
 * @property integer $task_status_id
 * @property integer $status
 * @property integer $control_baseline_id
 * @property string $created_on
 * @property string $target_date
 * @property string $task_name
 * @property string $task_description
 *
 * The followings are the available model relations:
 * @property Company $company
 * @property ControlBaseline $controlBaseline
 * @property Employee $employee
 * @property TaskFrequency $taskFrequency
 * @property TaskStatus $taskStatus
 * @property Users $user
 */
class Task extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'task';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('user_id, task_name', 'required'),
			array('company_id, employee_id, user_id, task_frequency_id, task_status_id, status, control_baseline_id', 'numerical', 'integerOnly'=>true),
			array('task_name', 'length', 'max'=>256),
			array('created_on, target_date, task_description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('task_id, company_id, employee_id, user_id, task_frequency_id, task_status_id, status, control_baseline_id, created_on, target_date, task_name, task_description', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'company' => array(self::BELONGS_TO, 'Company', 'company_id'),
			'controlBaseline' => array(self::BELONGS_TO, 'ControlBaseline', 'control_baseline_id'),
			'employee' => array(self::BELONGS_TO, 'Employee', 'employee_id'),
			'taskFrequency' => array(self::BELONGS_TO, 'TaskFrequency', 'task_frequency_id'),
			'taskStatus' => array(self::BELONGS_TO, 'TaskStatus', 'task_status_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'task_id' => 'Task',
			'company_id' => 'Company',
			'employee_id' => 'Employee',
			'user_id' => 'User',
			'task_frequency_id' => 'Task Frequency',
			'task_status_id' => 'Task Status',
			'status' => 'Status',
			'control_baseline_id' => 'Control Baseline',
			'created_on' => 'Created On',
			'target_date' => 'Target Date',
			'task_name' => 'Task Name',
			'task_description' => 'Task Description',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('task_id',$this->task_id);
		$criteria->compare('company_id',$this->company_id);
		$criteria->compare('employee_id',$this->employee_id);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('task_frequency_id',$this->task_frequency_id);
		$criteria->compare('task_status_id',$this->task_status_id);
		$criteria->compare('status',$this->status);
		$criteria->compare('control_baseline_id',$this->control_baseline_id);
		$criteria->compare('created_on',$this->created_on,true);
		$criteria->compare('target_date',$this->target_date,true);
		$criteria->compare('task_name',$this->task_name,true);
		$criteria->compare('task_description',$this->task_description,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Task the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/TaskController.php
<?php

require_once(Yii::app()->basePath.'/appinclude/Helper.php');

class TaskController extends GridViewController
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access user for CRUD operations
            'postOnly + get,delete', // we only allow deletion via POST request
            'ajaxOnly + get,delete,view',
        );
    }

    /**
     * Specifies the access user rules.
     * This method is used by the 'accessControl' filter.
     * @return array access user rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array(''),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('list','get','delete','view','edit'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionList()
    {
		mPermission::checkAccess($this, 'Compliance', 'Tasks');
        $employeeId = getGet('cuid');
        if ($employeeId !== null) {
            $listUrl = url('task/get',array('cuid'=>$employeeId));
        } else {
            $listUrl = url('task/get');
        }
		$this->render('vList', array('listUrl'=>$listUrl));
    }

    public function actionGet()
    {
		mPermission::checkAccess($this, 'Compliance', 'Tasks', Cons::ROLE_AUDITOR, 'json');
        $s = $this->getSearchParams();
        $employeeId = getGet('cuid');
        if ($employeeId !== null && Obscure::isObscure($employeeId) !== false) {
            $employeeId = Obscure::decode($employeeId);
        } else {
            $employeeId = null;
        }
        $json = Task_Ex::getTasksJson(Utils::contextCompanyId(),$s['pageSize'],$s['offsetBy'],$s['search'],$s['searchLogic'],$s['sort'],$employeeId);
        echo $json;
    }

    // Task Delete
    // override method called by ajaxDelete()
    protected function doDelete($id,$markStatusOnly=false)
    {
        return $this->doModelDelete($id,Task::model(),array('task_id'=>$id,'company_id' => Utils::contextCompanyId()),$markStatusOnly);
    }
    public function actionDelete()
    {
		mPermission::checkAccess($this, 'Compliance', 'Tasks', Cons::ROLE_AUTHOR, 'json');
		$id = $this->paramObscureId(); // will exit if bad param for security reasons
		echo $this->doDelete($id);
    }

    // overriden from base and called by $this->renderView() to get values and skipEncode for View feature
    protected function getViewValues($id,&$skipEncode)
    {
        $values = Task_Ex::getViewValues(Utils::contextCompanyId(),$id);
        $skipEncode = array('Description');
        return $values;
    }
    public function actionView()
    {
		mPermission::checkAccess($this, 'Compliance', 'Tasks', Cons::ROLE_AUDITOR);
        $this->renderView(Cons::LIC_TRIAL,Cons::ROLE_AUDITOR); // base GridViewController method calls override method getViewValues()
    }

    public function actionEdit()
    {
		mPermission::checkAccess($this, 'Compliance', 'Tasks', Cons::ROLE_AUTHOR);

        $id = $this->paramObscureId(false); // will exit if bad param for security reasons

        if (isset($id) && $id > 0) {
            $model = Task::model()->findByAttributes(array('task_id' => $id, 'company_id' => Utils::contextCompanyId()));
            if (!isset($model)) {
                badurl('User attempting wrongful access.');
            }
            $model->isNewRecord = false;
        } else {
            $model=new Task;
            $model->isNewRecord = true;
        }

        if (isset($_POST['Task'])) {
            $model->attributes=$_POST['Task'];
            $model->company_id = Utils::contextCompanyId();
            $model->user_id = userId();
            if (!empty($model->target_date)) {
                $model->target_date = DateHelper::FormatDateTimeString($model->target_date,'Y-m-d');
            }
            if ($model->validate()) {
                if ($model->save()) {
                    $this->redirect(url('task/list'));
                    return;
                } else {
                    $model->addError('task_name', "Failed to save changes. Try again.");
                    Yii::log(print_r($model->getErrors(), true), 'error', 'TaskController.actionEdit');
                }
            }
        }
        if (!empty($model->target_date)) {
            $model->target_date = DateHelper::FormatDateTimeString($model->target_date,'m/d/Y');
        }
        $this->render('vEdit',array('model'=>$model));
    }
}

protected/views/task/vEdit.php
<?
/* @var $this TaskController */
/* @var $model Task */
/* @var $form CActiveForm */
$this->pageTitle=Yii::app()->name.' - Edit Task';
?>

<script type="text/javascript" src="<?= url("3rdparty/tinymce/js/tinymce/tinymce.min.js"); ?>"></script>
<script type="text/javascript">
    tinymce.init({
        mode : "textareas",
        theme : "modern", menubar: false
    });
</script>

<h3>Edit Task</h3>


<div class="form">

	<? $form=$this->beginWidget('CActiveForm', array('action'=>url('task/edit',array('id'=>Obscure::encode($model->task_id))),
		'htmlOptions' => array('enctype' => 'multipart/form-data'),
		'id'=>'edit-form',
		'enableAjaxValidation'=>false,
	)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?= $form->errorSummary($model); ?>

	<div class="row">
		<?= $form->labelEx($model,'task_name'); ?>
		<?= $form->textField($model,'task_name',array('style'=>"width: 99%;")); ?>
		<?= $form->error($model,'task_name'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'employee_id'); ?>
		<select name="Task[employee_id]" id="Task_employee_id" style="width: 100%;">
			<option value="" <?= (empty($model->profile_id)) ? 'selected="selected"' : ''; ?>>no one</option>
			<? $users = Employee::model()->findAllByAttributes(array('company_id' => Utils::contextCompanyId()),array('order' => 'firstname ASC, lastname ASC')); ?>
			<? foreach ($users as $user) { ?>
				<option value="<?= $user->employee_id; ?>" <?= ($model->employee_id == $user->employee_id) ? 'selected="selected"' : ''; ?>><?= $user->firstname.' '.$user->lastname; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'employee_id'); ?>
	</div>
	
	<div class="row">
		<?= $form->labelEx($model,'task_description'); ?>
		<?= $form->textArea($model,'task_description',array('rows'=>'5','style'=>"width: 99%;")); ?>
		<?= $form->error($model,'task_description'); ?>
	</div>
	
	<div class="row">
		<?= $form->labelEx($model,'task_status_id'); ?>
		<select name="Task[task_status_id]" id="Task_task_status_id">
			<? $task_statuses = TaskStatus::model()->findAll(array('order' => 'task_status_id ASC')); ?>
			<? foreach($task_statuses as $ts) { ?>
				<option value="<?= $ts->task_status_id; ?>"  <?= ($model->task_status_id==$ts->task_status_id) ? 'selected="selected"' :'';?>><?= $ts->task_status_name; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'task_status_id'); ?>
	</div>
	
	<div class="row">
		<?= $form->labelEx($model,'target_date'); ?>
		<input name="Task[target_date]" id="Task_target_date" type="us-date" value="<?= $model->target_date; ?>">
		<?= $form->error($model,'target_date'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'task_frequency_id'); ?>
		<select name="Task[task_frequency_id]" id="Task_task_frequency_id">
			<? $task_frequency = TaskFrequency::model()->findAll(array('order' => 'task_frequency_id ASC')); ?>
			<? foreach($task_frequency as $tf) { ?>
				<option value="<?= $tf->task_frequency_id; ?>"  <?= ($model->task_frequency_id==$tf->task_frequency_id) ? 'selected="selected"' :'';?>><?= $tf->task_frequency_name; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'task_frequency_id'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'control_baseline_id'); ?>
		<select name="Task[control_baseline_id]" id="Task_control_baseline_id" style="width: 99%;">
			<option value="" <?= (empty($model->company_id)) ? 'selected="selected"' : ''; ?>>None</option>
			<? $controls = ControlBaseline_Ex::getRelatedControls(); ?>
			<? foreach ($controls as $control) { ?>
				<option value="<?= $control['control_baseline_id']; ?>" <?= ($model->control_baseline_id == $control['control_baseline_id']) ? 'selected="selected"' : ''; ?>><?= $control['category'].' - '.$control['title']; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'control_baseline_id'); ?>
	</div>

	<div class="row buttons">
		<?= CHtml::button('Save',array('id'=>"btnSave",'class'=>"btn btn-success")); ?>
		<?= CHtml::button('Cancel',array('id'=>"btnCancel",'class'=>"btn btn-primary")); ?>
	</div>

	<? $this->endWidget(); ?>

</div><!-- form -->

<script type="text/javascript">
	$(function(){
		$('input[type=us-date]').w2field('date');
		$("#btnSave").click(function(){
			$('#edit-form').submit();
			return false;
		});
		$("#btnCancel").click(function(){
			window.location = "<?= url('task/list'); ?>";
			return false;
		});
	});
</script>

protected/views/task/vList.php
<? $isAuthor = Utils::isRoleAuthor(); ?>
<script type="text/javascript">
    var _ajaxListGridColumns = [
        { field: 'task_id', caption: 'id', size: '0px', hidden: true, sortable: false,  resizable: false },
        { field: 'task_name', caption: 'Title', size: '100%', searchable: 'text', resizable: true, sortable: true },
        { field: 'task_status_name', caption: 'Status', size: '80px', searchable: 'text', resizable: true, sortable: true },
        { field: 'firstname', caption: 'Assigned To First Name', hidden: true, sortable: true, searchable: 'text' },
        { field: 'lastname', caption: 'Assigned To Last Name', hidden: true, sortable: true, searchable: 'text' },
        { field: 'employee_name', caption: 'Assigned To', size: '150px', resizable: true, sortable: true },
        { field: 'task_frequency_name', caption: 'Frequency', size: '80px', searchable: 'text', resizable: true, sortable: true },
        { field: 'target_date', caption: 'Target Date', size: '80px', searchable: 'date', resizable: true, sortable: true },
        { field: 'action', caption: 'Actions', size: '<?= ($isAuthor) ? '100px' : '55px'; ?>', hideable: false, sortable: false,  resizable: false,
            render: function (record, index, column_index) {
                <? if ($isAuthor) { ?>
                    var html = '<div>'
                        +'<a class="lnkView" href="" data-recid="'+record.recid+'">View</a>'
                        +'<span>&nbsp;</span>'
                        +'<a class="lnkEdit" href="<?= url('task/edit'); ?>/id/'+record.recid+'">Edit</a>'
                        +'<span>&nbsp;</span>'
                        +'<a class="lnkDelete" href="" data-recid="'+record.recid+'">Delete</a>'
                        +'</div>';
                <? } else { ?>
                    var html = '<div>'
                        +'<a class="lnkView" href="" data-recid="'+record.recid+'">View</a>'
                        +'</div>';
                <? } ?>
                return html;
            }
        }
    ];

    var _ajaxListGridAddFunction = false;

</script>
<?
/* @var $this TaskController */
/* @var $model Task */

    $gmAjaxListGrid = new gmAjaxListGrid();
    $gmAjaxListGrid->title = "<h2>Tasks</h2>";
    $gmAjaxListGrid->intro = "<p>Administrators and Authors can manage the compliance related tasks and assign them to a <a href=\"'.url('employee/list').'\" style=\"color: blue;\">User</a>.</p>";
    $gmAjaxListGrid->listUrl = $listUrl;
    $gmAjaxListGrid->controller = "task";
    $gmAjaxListGrid->recid = "task_id";
    $gmAjaxListGrid->allowAdd = $isAuthor;
    $gmAjaxListGrid->allowEdit = $isAuthor;
    $gmAjaxListGrid->allowDelete = $isAuthor;
    $gmAjaxListGrid->allowCopy = false;
    $gmAjaxListGrid->reloadOnCopy = false;
    AjaxListGridGadget::show($gmAjaxListGrid);
?>