protected/models/PolicyLibrary.php
<?php

/**
 * This is the model class for table "policy_library".
 *
 * The followings are the available columns in table 'policy_library':
 * @property integer $policy_library_id
 * @property integer $cat_id
 * @property integer $approved
 * @property integer $policy_type
 * @property integer $license_level
 * @property integer $policy_status_id
 * @property integer $status
 * @property integer $file_size
 * @property string $file_ext
 * @property string $file_type
 * @property string $file_name
 * @property string $doc_guid
 * @property string $doc_title
 * @property string $created_on
 * @property string $publish_date
 * @property string $expiry_date
 * @property string $author
 * @property string $keywords
 * @property string $description
 *
 * The followings are the available model relations:
 * @property Policy[] $policies
 * @property ControlCategory $cat
 * @property PolicyStatus $policyStatus
 */
class PolicyLibrary extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'policy_library';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('file_name, doc_guid, doc_title', 'required'),
			array('cat_id, approved, policy_type, license_level, policy_status_id, status, file_size', 'numerical', 'integerOnly'=>true),
			array('file_ext', 'length', 'max'=>10),
			array('file_type', 'length', 'max'=>127),
			array('file_name, doc_title, author', 'length', 'max'=>256),
			array('doc_guid', 'length', 'max'=>36),
			array('keywords', 'length', 'max'=>2000),
			array('created_on, publish_date, expiry_date, description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('policy_library_id, cat_id, approved, policy_type, license_level, policy_status_id, status, file_size, file_ext, file_type, file_name, doc_guid, doc_title, created_on, publish_date, expiry_date, author, keywords, description', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'policies' => array(self::HAS_MANY, 'Policy', 'policy_library_id'),
			'cat' => array(self::BELONGS_TO, 'ControlCategory', 'cat_id'),
			'policyStatus' => array(self::BELONGS_TO, 'PolicyStatus', 'policy_status_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'policy_library_id' => 'Policy Library',
			'cat_id' => 'Cat',
			'approved' => 'Approved',
			'policy_type' => 'Policy Type',
			'license_level' => 'License Level',
			'policy_status_id' => 'Policy Status',
			'status' => 'Status',
			'file_size' => 'File Size',
			'file_ext' => 'File Ext',
			'file_type' => 'File Type',
			'file_name' => 'File Name',
			'doc_guid' => 'Doc Guid',
			'doc_title' => 'Doc Title',
			'created_on' => 'Created On',
			'publish_date' => 'Publish Date',
			'expiry_date' => 'Expiry Date',
			'author' => 'Author',
			'keywords' => 'Keywords',
			'description' => 'Description',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('policy_library_id',$this->policy_library_id);
		$criteria->compare('cat_id',$this->cat_id);
		$criteria->compare('approved',$this->approved);
		$criteria->compare('policy_type',$this->policy_type);
		$criteria->compare('license_level',$this->license_level);
		$criteria->compare('policy_status_id',$this->policy_status_id);
		$criteria->compare('status',$this->status);
		$criteria->compare('file_size',$this->file_size);
		$criteria->compare('file_ext',$this->file_ext,true);
		$criteria->compare('file_type',$this->file_type,true);
		$criteria->compare('file_name',$this->file_name,true);
		$criteria->compare('doc_guid',$this->doc_guid,true);
		$criteria->compare('doc_title',$this->doc_title,true);
		$criteria->compare('created_on',$this->created_on,true);
		$criteria->compare('publish_date',$this->publish_date,true);
		$criteria->compare('expiry_date',$this->expiry_date,true);
		$criteria->compare('author',$this->author,true);
		$criteria->compare('keywords',$this->keywords,true);
		$criteria->compare('description',$this->description,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return PolicyLibrary the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/PolicylibraryController.php
<?php
require_once(Yii::app()->basePath.'/appinclude/Helper.php');

class PolicylibraryController extends GridViewController
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access user for CRUD operations
            'postOnly + get,delete,copy', // we only allow deletion via POST request
            'ajaxOnly + get,delete,view,copy',
        );
    }

    /**
     * Specifies the access user rules.
     * This method is used by the 'accessControl' filter.
     * @return array access user rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array(''),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('list','get','view','download','copy'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'edit' and 'delete' actions
                'actions'=>array('delete','edit'),
                'expression'=>'!user()->isGuest && Utils::isSuper()',
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionList()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library');
		$this->render('vList');
    }

    public function actionGet()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library', null, 'json');
        $s = $this->getSearchParams();
        $json = PolicyLibrary_Ex::getPolicyLibraryJson($s['pageSize'],$s['offsetBy'],$s['search'],$s['searchLogic'],$s['sort']);
        echo $json;
    }

    public function actionDownload()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library', Cons::ROLE_AUTHOR);
        // will send headers and exit or show a message
        $this->downloadFile(mDownloadFile::PolicyLibrary,Cons::LIC_TRIAL,Cons::ROLE_AUTHOR);
    }

    // PolicyLibrary Delete
    // can override to do post delete actions
    protected function postDelete($id,$model,$markStatusOnly=false) {
        return PolicyLibrary_Ex::removeFile($model);
    }
    // override method called by ajaxDelete()
    protected function doDelete($id,$markStatusOnly=false)
    {
        return $this->doModelDelete($id,PolicyLibrary::model(),array('policy_library_id'=>$id),$markStatusOnly);
    }
    public function actionDelete()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library', Cons::ROLE_ADMIN, 'json');
        $markStatusOnly = true;
        if (Utils::isSuper()) {
			$id = $this->paramObscureId(); // will exit if bad param for security reasons
			echo $this->doDelete($id);
        } else {
            $status = 'error';
            $message = 'Your role is not authorized to delete the policy library document.';
            echo json_encode(array('status' => $status, 'message'=>$message));
        }
    }

    // overriden from base and called by $this->renderView() to get values and skipEncode for View feature
    protected function getViewValues($id,&$skipEncode)
    {
        $values = PolicyLibrary_Ex::getViewValues($id);
        $skipEncode = array('Description');
        return $values;
    }
    public function actionView()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library', Cons::ROLE_AUTHOR);
		$id = $this->paramObscureId(); // will exit if bad param for security reasons
		$policyLibrary = PolicyLibrary::model()->findByAttributes(array('policy_library_id' => $id));
		if ($policyLibrary->license_level <= getSessionVar('license_level')) {
			$this->renderView(Cons::LIC_TRIAL,Cons::ROLE_AUTHOR); // base GridViewController method calls override method getViewValues()
		} else {
			echo "<div><strong>Available in the paid version.</strong></div>";
		}

    }

    // PolicyLibrary Copy
    // override method called by ajaxCopy()
    // function is to copy and returns params for json staus and message
    // can be overridden for other use cases
    protected function doCopy($id)
    {
        $status = PolicyLibrary_Ex::copyPolicy($id,Utils::contextCompanyId(),userId(),$message);
        return array('status'=>$status,'message'=>$message);
    }
    public function actionCopy()
    {
		mPermission::checkAccess($this, 'Policy Documents', 'Policy Library', Cons::ROLE_AUTHOR, 'json');
        echo $this->ajaxCopy(Cons::LIC_TRIAL,Cons::ROLE_AUTHOR);
    }

    public function actionEdit()
    {
        if (Utils::isSuper()) {
            $id = $this->paramObscureId(false); // will exit if bad param for security reasons

            if (isset($id) && $id > 0) {
                $model = PolicyLibrary::model()->findByAttributes(array('policy_library_id' => $id));
                if (!isset($model)) {
                    badurl('User attempting wrongful access.');
                }
                $model->isNewRecord = false;
            } else {
                $model=new PolicyLibrary;
                $model->isNewRecord = true;
            }

            if(isset($_POST['PolicyLibrary']))
            {
                $model->attributes=$_POST['PolicyLibrary'];
                if (!empty($model->publish_date)) {
                    $model->publish_date = DateHelper::FormatDateTimeString($model->publish_date,'Y-m-d');
                }
                if (!empty($model->expiry_date)) {
                    $model->expiry_date = DateHelper::FormatDateTimeString($model->expiry_date,'Y-m-d');
                }
                if ($model->isNewRecord) {
                    $model->doc_guid = Utils::create_guid();
                    $model->publish_date = date('Y-m-d');
                }

                $fileUrl = false;
                $tmpFileFullPath = false;
                // handle PolicyLibrary file upload
                if (isset($_FILES['PolicyLibrary'])) {
                    if (!empty($_FILES['PolicyLibrary']['name'])) {
                        $tmpFileFullPath = $_FILES['PolicyLibrary']['tmp_name'];
                        $model->file_size = $_FILES['PolicyLibrary']['size'];
                        $model->file_type = $_FILES['PolicyLibrary']['type'];
                        $model->file_name = $_FILES['PolicyLibrary']['name'];
                        $model->file_ext = pathinfo($_FILES['PolicyLibrary']['name'], PATHINFO_EXTENSION);
                    }
                }

                if($model->validate())
                {
                    if ($model->isNewRecord) {
                        if ($tmpFileFullPath !== false) {
                            $fileUrl = PolicyLibrary_Ex::saveFile($tmpFileFullPath, $model);
                            if ($fileUrl !== false) {
                                if ($model->save()) {
                                    $this->redirect(url('policylibrary/list'));
                                    return;
                                } else {
                                    $model->addError('doc_title', "Failed to save policy library document. Try again.");
                                }
                            } else {
                                $model->addError('file_name', "Failed to upload Policy Library File.");
                            }
                        } else {
                            $model->addError('file_name', "Policy Library File is required. Choose a file to upload.");
                        }
                    } else if ($model->save()) {
                        if ($tmpFileFullPath !== false) {
                            $fileUrl = PolicyLibrary_Ex::saveFile($tmpFileFullPath, $model);
                            if ($fileUrl !== false) {
                                $this->redirect(url('policylibrary/list'));
                                return;
                            } else {
                                $model->addError('file_name', "Failed to upload Policy Library File.");
                            }
                        } else {
                            $this->redirect(url('policylibrary/list'));
                            return;
                        }
                    } else {
                        $model->addError('doc_title', "Failed to save changes. Try again.");
                        Yii::log(print_r($model->getErrors(), true), 'error', 'PolicylibraryController.actionEdit');
                    }
                }
            }
            if (!empty($model->publish_date)) {
                $model->publish_date = DateHelper::FormatDateTimeString($model->publish_date,'m/d/Y');
            }
            if (!empty($model->expiry_date)) {
                $model->expiry_date = DateHelper::FormatDateTimeString($model->expiry_date,'m/d/Y');
            }
            $this->render('vEdit',array('model'=>$model));
        } else {
            badurl('Your role is not authorized to edit the policy library document.');
        }
    }
}

protected/views/policylibrary/vEdit.php
<?
/* @var $this PolicylibraryController */
/* @var $model PolicyLibrary */
/* @var $form CActiveForm */
$this->pageTitle=Yii::app()->name.' - Edit Policy Library Document';
?>

<script type="text/javascript" src="<?= url("3rdparty/tinymce/js/tinymce/tinymce.min.js"); ?>"></script>
<script type="text/javascript">
	tinymce.init({
        mode : "textareas",
        theme : "modern", menubar: false
    });
</script>

<h3>Edit Policy Library Document</h3>

<div class="form">

	<? $form=$this->beginWidget('CActiveForm', array('action'=>url('policylibrary/edit',array('id'=>Obscure::encode($model->policy_library_id))),
		'htmlOptions' => array('enctype' => 'multipart/form-data'),
		'id'=>'edit-form',
		'enableAjaxValidation'=>false,
	)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?= $form->errorSummary($model); ?>

	<div class="row">
		<label>Title <span class="required">*</span></label>
		<?= $form->textField($model,'doc_title',array('style'=>"width: 99%;")); ?>
		<?= $form->error($model,'doc_title'); ?>
	</div>

	<? if (!empty($model->publish_date)) { ?>
		<div class="row">
			<?= $form->labelEx($model,'publish_date'); ?>
			<p style="color: black;"><?= $model->publish_date; ?></p>
		</div>
	<? } ?>

	<div class="row">
		<label>Review Date</label>
		<input name="PolicyLibrary[expiry_date]" id="PolicyLibrary_expiry_date" type="us-date" value="<?= $model->expiry_date; ?>">
		<?= $form->error($model,'expiry_date'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'author'); ?>
		<?= $form->textField($model,'author',array('style'=>"width: 99%;")); ?>
		<?= $form->error($model,'author'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'keywords'); ?>
		<?= $form->textField($model,'keywords',array('style'=>"width: 99%;")); ?>
		<?= $form->error($model,'keywords'); ?>
	</div>

	<? /* dave says category not needed now
	<div class="row">
		<?= $form->labelEx($model,'cat_id'); ?>
		<select name="PolicyLibrary[cat_id]" id="PolicyLibrary_cat_id" style="width: 320px;">
			<? $cats = ControlCategory_Ex::getCategory(); ?>
			<? foreach ($cats as $cat) { ?>
				<option value="<?= $cat['control_category_id']; ?>" <?= ($model->cat_id == $cat['control_category_id']) ? 'selected="selected"' : ''; ?>><?= $cat['category']; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'cat_id'); ?>
	</div>
    */ ?>

	<div class="row">
		<label>Type</label>
		<select name="PolicyLibrary[policy_type]" id="policy_type" style="width: 120px;">
			<? foreach (mPolicy::$PolicyTypes as $policyTypeId=>$policyType) { ?>
				<option value="<?= $policyTypeId; ?>" <?= ($model->policy_type == $policyTypeId) ? 'selected="selected"' : ''; ?>><?= $policyType; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'policy_type'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'approved'); ?>
		<select name="PolicyLibrary[approved]" id="PolicyLibrary_approved">
			<option value="0"  <?= ($model->approved=='0') ? 'selected="selected"' :'';?>>Un-Approved</option>
			<option value="1"  <?= ($model->approved=='1') ? 'selected="selected"' :'';?>>Approved</option>
		</select>
		<?= $form->error($model,'approved'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'policy_status_id'); ?>
		<select name="PolicyLibrary[policy_status_id]" id="PolicyLibrary_policy_status_id">
			<? $policystatus = PolicyStatus::model()->findAll(array('order' => 'policy_status_id ASC')); ?>
			<? foreach($policystatus as $ps) { ?>
				<option value="<?= $ps->policy_status_id; ?>"  <?= ($model->policy_status_id==$ps->policy_status_id) ? 'selected="selected"' :'';?>><?= $ps->policy_status_name; ?></option>
			<? } ?>
		</select>
		<?= $form->error($model,'policy_status_id'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'description'); ?>
		<?= $form->textArea($model,'description',array('rows'=>'5','style'=>"width: 99%;")); ?>
		<?= $form->error($model,'description'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'file_name'); ?>
		<? if (empty($model->file_name)) { ?>
			<p>Choose file to upload a document.</p>
		<? } else { ?>
			<p>Current document: <b><?= $model->file_name; ?></b></p>
			<p>Optionally, you may choose another file to upload to replace the current document.</p>
		<? } ?>
		<input type="file" name="PolicyLibrary" id="PolicyLibrary" value="" style="width: 99%; border: none; background: transparent;" />
	</div>

	<div class="row buttons">
		<?= CHtml::button('Save',array('id'=>"btnSave",'class'=>"btn btn-success")); ?>
		<?= CHtml::button('Cancel',array('id'=>"btnCancel",'class'=>"btn btn-primary")); ?>
	</div>

	<? $this->endWidget(); ?>

</div><!-- form -->

<script type="text/javascript">
	$(function(){
		$('input[type=us-date]').w2field('date');
		$("#btnSave").click(function(){
			$('#edit-form').submit();
			return false;
		});
		$("#btnCancel").click(function(){
			window.location = "<?= url('policylibrary/list'); ?>";
			return false;
		});
	});
</script>

protected/views/policylibrary/vList.php
<? $isAuthor = Utils::isRoleAuthor(); ?>
<? $isSuperOwner = (Utils::isSuper() && Utils::isRoleOwner()); ?>
<script type="text/javascript">
    var _ajaxListGridColumns = [
        { field: 'policy_library_id', caption: 'id', size: '0px', hidden: true, sortable: false,  resizable: false },
        { field: 'doc_title', caption: 'Title', size: '100%', searchable: 'custom', resizable: true, sortable: true,
            render: function (record, index, column_index) {
				var html = '';
				<? if (getSessionVar('license_level') > Cons::LIC_TRIAL) { ?>
					html = '<span><a class="lnkDownload" href="<?= url('policylibrary/download'); ?>/id/'+record.recid+'">'+record.doc_title+'</a></span>';
				<? } else { ?>
					if (record.license_level <= <?= getSessionVar('license_level'); ?>) {
						html = '<span style="color: blue; font-weight: bold;"><a class="lnkDownload" href="<?= url('policylibrary/download'); ?>/id/'+record.recid+'">'+record.doc_title+'</a></span>';
					} else {
						html = '<span style="color: lightgrey;">' + record.doc_title + '</span>';
					}
				<? } ?>
				return html;
            }
        },
        { field: 'author', caption: 'Author', size: '150px', searchable: 'custom', resizable: true, sortable: true },
		{ field: 'policy_type', caption: 'Type', size: '70px', searchable: 'custom', resizable: true, sortable: true },
		<? if (getSessionVar('license_level') <= Cons::LIC_TRIAL) { ?>
			{ field: 'license_level_name', caption: 'License', size: '70px', searchable: 'custom', resizable: true, sortable: true,
				render: function (record, index, column_index) {
					var html = '';
					if (record.license_level <= <?= getSessionVar('license_level'); ?>) {
						html = '<span style="color: blue; font-weight: bold;">' + record.license_level_name + '</span>';
					} else {
						html = '<span style="color: lightgrey;">' + record.license_level_name + '</span>';
					}
					return html;
				}
			},
		<? } ?>
        <? if (Utils::isSuper()) { // only admins should see non-published policies ?>
        	{ field: 'policy_status_name', caption: 'Status', size: '60px', searchable: 'text', resizable: true, sortable: true },
        <? } ?>
        { field: 'expiry_date', caption: 'Updated', size: '75px', searchable: 'date', resizable: true, sortable: true },
        { field: 'action', caption: 'Actions', size: '<?= ($isSuperOwner) ? '130px' : '70px'; ?>', hideable: false, sortable: false,  resizable: false, hidden: <?= (!$isAuthor) ? 'true':'false'; ?>,
            render: function (record, index, column_index) {
                <? if ($isAuthor) { ?>
                var html = '<div>'
                    +'<a class="lnkView" href="" data-recid="'+record.recid+'">View</a>'
                    +'<span>&nbsp;</span>'
                    +'<a class="lnkCopy" href="" data-recid="'+record.recid+'">Copy</a>'
                    <? if ($isSuperOwner) { ?>
                        +'<span>&nbsp;</span>'
                        +'<a class="lnkEdit" href="<?= url('policylibrary/edit'); ?>/id/'+record.recid+'">Edit</a>'
                        +'<span>&nbsp;</span>'
                        +'<a class="lnkDelete" href="" data-recid="'+record.recid+'">Delete</a>'
                    <? } ?>
                    +'</div>';
                <? } else { ?>
                var html = '<div></div>';
                <? } ?>
                return html;
            }
        }
    ];

    var _ajaxListGridAddFunction = false;

</script>
<?
/* @var $this PolicylibraryController */
/* @var $model PolicyLibrary */

    $gmAjaxListGrid = new gmAjaxListGrid();
    $gmAjaxListGrid->title = "<h2>Policy Library</h2>";
    if ($isAuthor) {
        $gmAjaxListGrid->intro = "<p>Click on the <strong>Title</strong> to download the policy document.</p>";
    }
    $gmAjaxListGrid->controller = "policylibrary";
    $gmAjaxListGrid->recid = "policy_library_id";
    $gmAjaxListGrid->allowAdd = $isSuperOwner;
    $gmAjaxListGrid->allowEdit = $isSuperOwner;
    $gmAjaxListGrid->allowDelete = $isSuperOwner;
    $gmAjaxListGrid->allowCopy = $isAuthor;
    $gmAjaxListGrid->reloadOnCopy = false;
	$gmAjaxListGrid->customSearch = array(
		// bad gadget design forces for definition of preceding search fields to show the searchable fields in the right order
		array(
			'field' => 'doc_title',
			'caption' => 'Title',
			'type' => 'text'
		),
		array(
			'field' => 'author',
			'caption' => 'Author',
			'type' => 'text'
		),
		array(
			'field' => 'policy_type',
			'caption' => 'Type',
			'type' => 'list',
			'hidden' => (empty(mPolicy::$PolicyTypes)) ? true : false,
			'options' => array(
				'items' => mPolicy::$PolicyTypes
			)
		),
	);
    AjaxListGridGadget::show($gmAjaxListGrid);
?>