protected/controllers/WizardController.php
<?php

require_once(Yii::app()->basePath.'/appinclude/Helper.php');

class WizardController extends Controller
{
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + ', // we only allow deletion via POST request
            'ajaxOnly + ',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array(''),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('control','complete', 'inherentriskscore'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionControl()
    {
		mPermission::checkAccess($this, 'Compliance', 'Control Wizard');
        $invite_guid = getSessionVar('invite_guid');
        if (!empty($invite_guid)) {
            $this->redirect(array('invite/open'));
        }

        $showAllQuestions = getGet('all',false);
        $id = $this->paramObscureId(false); // will exit if bad param for security reasons

        $company_id = Utils::contextCompanyId();
        $company = Company::model()->findByPk($company_id);
        if (isset($company)) {
            if (isset($id) && $id > 0) {
                $model = CompanyInfo::model()->findByPk($id);
                if (!isset($model)) {
                    badurl('User attempting wrongful access.');
                }
                $model->isNewRecord = false;
            } else {
                $model = CompanyInfo::model()->findByAttributes(array('company_id' => $company_id));
                if (!isset($model)) {
                    $model = new CompanyInfo;
                    $model->isNewRecord = true;
                    $model->country = "US";
                } else {
                    $model->isNewRecord = false;
                }
            }
            // let's keep the names in sync between the private and public data
            // Company_info is private and Company is public (meaning user can see those fields.)
            $model->business_name = $company->name;

            if (isset($_POST['CompanyInfo'])) {
                $model->attributes = $_POST['CompanyInfo'];
                $model->company_id = $company_id;
                $model->user_id = userId();
                $model->updated_on = date('Y-m-d H:i:s');
                if ($model->isNewRecord) {
                    $model->created_on = date('Y-m-d H:i:s');
                }

                if ($model->validate()) {
                    if ($model->save()) {
                        $company->name = $model->business_name;
                        if (!$company->save()) {
                            Yii::log('Interesting failed to save company.name to db.', 'error', 'WizardController.actionControl');
                        }
                        $mWizardRules = new mWizardRules();

                        // return count of controls add to the baseline, note: renames Company X to the business_name
                        $count = $mWizardRules->copyControlsByRules($model,userId());

                        // calculate total risk score and save
						$wizardInherentRiskScore = Wizard_Ex::calculateWizardInherentRisk($model->attributes);

						$this->redirect(url('wizard/complete',array('count'=>$count)));
                        return;
                    } else {
                        $model->addError('business_name', "Failed to save wizard results. Try again or contact technical support.");
                        Yii::log(print_r($model->getErrors(), true), 'error', 'WizardController.actionControl');
                    }
                }
            }
            $this->pageTitle = Yii::app()->name . ' - Control Baseline';
            $this->render('vWizard', array('model' => $model, 'showAllQuestions' => $showAllQuestions));
        } else {
            Yii::log('Company is missing! Should not be!', 'error', 'WizardController.actionControl');
            $this->redirect(url('site/accountoptions'));
        }
    }

    public function actionComplete()
    {
		mPermission::checkAccess($this, 'Compliance', 'Control Wizard', Cons::ROLE_AUTHOR);
        $count = getGet('count',0);
		$model = CompanyInfo::model()->findByAttributes(array('company_id' => Utils::contextCompanyId()));
		if (isset($model)) {
			$wizardInherentRiskScore = Wizard_Ex::calculateWizardInherentRisk($model->attributes);
		}
        $this->render('vComplete',array('count'=>$count, 'wizardInherentRiskScore' => $wizardInherentRiskScore));
    }
    
    public function actionInherentriskscore()
    {
		mPermission::checkAccess($this, 'Compliance', 'Cyber Inherent Risk');
        $model = CompanyInfo::model()->findByAttributes(array('company_id' => Utils::contextCompanyId()));
        if (isset($model)) {
            $companyName = $model->business_name;
            $wizardInherentRiskScore = Wizard_Ex::calculateWizardInherentRisk($model->attributes);
        } else {
            $companyName = Utils::contextCompanyName();
            $wizardInherentRiskScore = Wizard_Ex::calculateWizardInherentRisk();
        }
        
        $this->render('vInherentRiskScore',
			array('wizardInherentRiskScore' => $wizardInherentRiskScore, 'companyName' => $companyName, 'updatedOn'=>$model->updated_on));
    }
}

protected/views/wizard/_vStep1.php
<?php
/* @var $this WizardController */
/* @var $model CompanyInfo */
/* @var $form CActiveForm */
$labelClass = "control-label col-md-12 col-sm-12 col-xs-12";
$answerClass = "col-md-12 col-sm-12 col-xs-12";
$inputClass = "form-control col-md-12 col-sm-12 col-xs-12";
/*
  `business_name` varchar(100) DEFAULT NULL,
  `num_employees` varchar(10) DEFAULT NULL COMMENT '[1-10, 11-100, 101-1000, 1000+]',
  `address` varchar(256) DEFAULT NULL COMMENT 'Business Location',
  `city` varchar(60) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zipcode` varchar(16) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  `publicly_traded` TINYINT(1) DEFAULT NULL COMMENT 'all fields are default null until answered by real human',
  `primary_business_type` varchar(60) DEFAULT NULL,
  `critical_infrastructure` TINYINT(1) DEFAULT NULL COMMENT 'yes,no,not sure - end of step1 wizard questions',
 */
?>
        <h2 class="StepTitle">Getting Started</h2>
        <p>
            Welcome to the Security Setup Wizard.
            The Wizard will help you determine the elements of your information security program.
            In the followings steps we will ask for information about your business that will help refine the program.
            (Don’t worry, you can always change answers later.)
        </p>
        <h2 class="StepTitle">Step 1: Business Profile</h2>
        <p>To get started, first we need to gather some general information about your business.</p>

        <div class="form-group">
            <label class="<?= $labelClass; ?>" for="CompanyInfo_business_name">Business Name</label>
            <div class="<?= $answerClass; ?>">
                <?= $form->textField($model,'business_name',array('size'=>30,'maxlength'=>100,'class'=>$inputClass)); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="<?= $labelClass; ?>" for="CompanyInfo_num_employees">Approximate Number of Employees</label>
            <div class="<?= $answerClass; ?>">
                <?= $form->radioButtonList($model,'num_employees',
                    array(
                        '1-50' => '1-50',
                        '51-500' => '51-500',
                        '501-5000' => '501-5000',
                        '5000+' => '5000+'
                    ),
                    array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span>')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="CompanyInfo_address" class="<?= $labelClass; ?>">Address of your primary business location</label>
            <div class="<?= $answerClass; ?>">
                <?= $form->textField($model,'address',array('size'=>30,'maxlength'=>100,'class'=>$inputClass)); ?>
            </div>

            <div style="display: inline-block; float: left">
                <label for="CompanyInfo_city" class="<?= $labelClass; ?>">City</label>
                <div class="<?= $answerClass; ?>">
                    <?= $form->textField($model,'city',array('size'=>32,'maxlength'=>60,'class'=>"form-control form-section col-md-3 col-sm-12 col-xs-12")); ?>
                </div>
            </div>
            <div style="display: inline-block; float: left">
                <label for="CompanyInfo_state" class="<?= $labelClass; ?>">State</label>
                <div class="<?= $answerClass; ?>">
                    <? $states = States::getStates(array('US','US TERRITORIES','CANADA')); ?>
                    <?= $form->dropDownList($model,'state',$states,array('class'=>"form-control form-section col-md-3 col-sm-12 col-xs-12")); ?>
                </div>
            </div>
            <div style="display: inline-block; float: left">
                <label for="CompanyInfo_zipcode" class="<?= $labelClass; ?>">Zipcode</label>
                <div class="<?= $answerClass; ?>">
                    <?= $form->textField($model,'zipcode',array('size'=>11,'maxlength'=>20,'class'=>"form-control form-section col-md-3 col-sm-12 col-xs-12")); ?>
                </div>
            </div>
            <div style="display: inline-block; float: left">
                <label for="CompanyInfo_country" class="<?= $labelClass; ?>">Country</label>
                <div class="<?= $answerClass; ?>">
                    <?= $form->dropDownList($model,'country',Country::getCountries(),array('class'=>"form-control form-section col-md-3 col-sm-12 col-xs-12")); ?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        
        <div class="form-group">
            <label class="<?= $labelClass; ?>" for="CompanyInfo_num_business_locations">Approximately how many business locations do you have?</label>
            <div class="<?= $answerClass; ?>">
                <?= $form->radioButtonList($model,'num_business_locations',
                    array(
                        '0' => 'None (Virtual)',
                        '1' => 'Single',
                        '2-10' => 'Small (2-10 locations)',
                        '10-100' => 'Medium (10 - 100 locations)', 
                        '100+' => 'Large (100+ locations)'
                    ),
                    array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
            </div>
        </div>
        
        <div class="form-group">
            <label for="CompanyInfo_primary_business_type" class="<?= $labelClass; ?>">Primary Business Type</label>
            <div class="<?= $answerClass; ?>">
                <?= $form->dropDownList($model,'primary_business_type',Industries::getKeyVal(),array('class'=>"form-control form-section col-md-12 col-sm-12 col-xs-12")); ?>
            </div>
        </div>

protected/views/wizard/_vStep2.php
<?
/* @var $this WizardController */
/* @var $model CompanyInfo */
/* @var $form CActiveForm */
//`security_maturity` TINYINT(1) DEFAULT NULL COMMENT 'step 2 Low, Med, Hi',
?>
<h2 class="StepTitle">Step 2: Target Security Posture</h2>
<p>
    Overall, what level of security maturity do you wish to adopt for your organization?
</p>
<p>
    A "LOW" or Basic security level might be appropriate for an organization that is does not handle sensitive data of
    customers, such as a service organization or manufacturer. A “Moderate” security level may be appropriate for
    organizations that collect sensitive data and want to establish security best practices.
    A "HIGH" security level might be required highly regulated industries that store sensitive customer information.
    The default for most organizations will be "MODERATE."
<p>
<div class="form-group" style="margin-top: 20px;">
    <label for="CompanyInfo_security_maturity" class="<?= $labelClass; ?>">Target Level of Security (Security Maturity)</label>
    <div class="<?= $answerClass; ?>" style="margin: 20px;">
        <?= $form->radioButtonList($model,'security_maturity',
            array('1'=>'Low - Basic Security','2'=>'Moderate – Moderate Security','3'=>'High – High Security'),
            array('class'=>$inputClass." flat",'separator'=>'<br/><br/>')); ?>
    </div>
</div>

protected/views/wizard/_vStep3.php
<?
/* @var $this WizardController */
/* @var $model CompanyInfo */
/* @var $form CActiveForm */

?>
<h2 class="StepTitle">Step 3: Business Data Profile</h2>
<p>
    Next we need to understand the types of data you collect and process.
    This not only determines your security requirements but your potential regulatory requirements and liability in case of breach.
</p>

<div class="form-group">
    <label for="CompanyInfo_highly_sensitive_data" class="<?= $labelClass; ?>">1. How many different types of data do you collect, store or process from customers that they would consider highly sensitive?  If yes, how many types of data?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'highly_sensitive_data',
            array(
                '0' => 'None - We do not process sensitive data',
                '1' => 'Single - Single Data Type (No PII – Personally Identifiable Information)',
                '2' => 'Single PII - Single Type of PII  (One primary PII)',
                '3' => 'Some - Multiple Data Types (Still No PII)',
                '4' => 'All - Multiple Types (both PII and non PII)'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
    </div>
</div>

<div class="form-group">
    <label for="CompanyInfo_individual_consumer_data" class="<?= $labelClass; ?>">2. Approximately how many records does your organization handle on individual consumers that would be considered “personally identifiable”?  (For example, social security numbers, Driver’s License numbers, bank account numbers or other financial information that is not credit card data.) </label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'individual_consumer_data',
            array(
                '0' => 'None',
                '1' => 'Less than 500',
                '2' => '500 to 5000', 
                '3' => '5000 to 50,000', 
                '4' => 'Greater than 50,000'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
    </div>
</div>
<div class="form-group">
    <label for="CompanyInfo_credit_card_data" class="<?= $labelClass; ?>">3. Do you accept credit card payments or otherwise process/store credit card data (PCI-DSS)?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'credit_card_data',
            array(
                '0' => 'No',
                '1' => 'Yes',
                '2' => 'Not sure'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span>')); ?>
    </div>
</div>
<div class="form-group">
    <label for="CompanyInfo_individual_health_data" class="<?= $labelClass; ?>">4. Do you process or store electronic or paper health records (ePHI) about individuals?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'individual_health_data',
            array(
                '0' => 'No',
                '1' => 'Yes',
                '2' => 'Not sure'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span>')); ?>
    </div>
</div>

protected/views/wizard/_vStep4.php
<?
/* @var $this WizardController */
/* @var $model CompanyInfo */
/* @var $form CActiveForm */
?>
<h2 class="StepTitle">Step 4: User Access to Information</h2>
<p>
    In this section we determine how employees and contractor access your sensitive data.
</p>

<div class="form-group">
    <label for="CompanyInfo_employee_mobile_customer_data" class="<?= $labelClass; ?>">1. How many employees and regular contractors have sensitive customer data on mobile devices (including laptops, tablets, smartphones)?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'employee_mobile_customer_data',
            array(
                '0' => 'None',
                '1' => 'Limited (< 5% of workforce)',
                '2' => 'Some (5 - 25% of workforce)', 
                '3' => 'Moderate (25 - 50% of workforce)', 
                '4' => 'Most ( > 50% of workforce)'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
    </div>
</div>

<div class="form-group">
    <label for="CompanyInfo_remote_network_access" class="<?= $labelClass; ?>">2. About how many employees have remote access to your networks?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'remote_network_access',
            array(
                '0' => 'None - No Remote Access',
                '1' => 'Limited (< 5% of workforce)', 
                '2' => 'Some (5 - 25% of workforce)', 
                '3' => 'Moderate (25 - 50% of workforce)', 
                '4' => 'Most ( > 50% of workforce)'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
    </div>
</div>

<div class="form-group">
    <label for="CompanyInfo_third_party_data" class="<?= $labelClass; ?>">3. About how many third parties (suppliers, service providers)? do you use to store or process customer information?</label>
    <div class="<?= $answerClass; ?>">
        <?= $form->radioButtonList($model,'third_party_data',
            array(
                '0' => 'None',
                '1' => 'Single Primary ',
                '2' => 'Minimal (2 - 25)', 
                '3' => 'Moderate (26 - 100)', 
                '4' => 'High (> 100)'
            ),
            array('class'=>$inputClass." flat",'separator'=>'<span class="sep-radios"></span><br/>')); ?>
    </div>
</div>

protected/views/wizard/vComplete.php
<?
	$totalScore = $wizardInherentRiskScore['total_score'];
	$maxScore = $wizardInherentRiskScore['max_score'];
?>
<div class="x_panel">
    <div class="x_title">
        <h3>Security Baseline Complete!</h3>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <h4>Congratulations!</h4>
        <p>You have established the baseline for your information security program.
        We have selected a group of<?= ($count > 1) ? ' '.$count : ''; ?> security functions (“controls”) that define your program.<br />
        Your next step is to evaluate each of these Controls and see how they apply to your business.
        </p>
        
        <div class="row">
			<div class="col-xs-12 col-md-6">
				<h4 style="padding: 16px 0 16px 0;">What would you like to do next?</h4>
				<? /*div class="col-xs-12 col-md-12" style="padding-bottom:10px;">
					<a href="<?= url('cyberriskscore/Newassessment'); ?>" class="btn btn-primary">1.&nbsp;&nbsp;Take Cyber Risk Assessment</a>
				</div */?>

				<div class="col-xs-12 col-md-12" style="padding-bottom:10px;">
					<a href="<?= url('controlbaseline/list'); ?>" class="btn btn-primary">1.&nbsp;&nbsp;Review/Refine Security Baseline</a>
				</div>

				<div class="col-xs-12 col-md-12" style="padding-bottom:10px;">
					<a href="<?= url('reportsituation'); ?>" class="btn btn-primary">2.&nbsp;&nbsp;Review Situation Report</a>
				</div>

				<div class="col-xs-12 col-md-12">
					<a href="<?= url('policy/list'); ?>" class="btn btn-primary">3.&nbsp;&nbsp;Begin developing Security Policies for your program</a>
				</div>
			</div>
			<div class="col-xs-12 col-md-6">
				<div class="x_panel">
					<div class="x_content">
						<h3 class="x_content text-center">Cyber Inherent Risk Score</h3>
						<div id="inherentRiskReportChart" style="height:270px;"></div>
						<div class="text-center">
							<p style="font-size:120%; font-weight: bold;">
								<strong>Inherent Risk:</strong>
								<? $percentage = ($totalScore / $maxScore) * 100; ?>
								<? $maturity_level = ''; ?>
								<? if($percentage > 90) { ?>
									<? $maturity_level = 'EXTREMELY_HIGH'; ?>
									<span style="color: #FF0000;">Extremely High</span>
								<? } else if($percentage > 70) { ?>
									<? $maturity_level = 'HIGH'; ?>
									<span style="color: #FFA75B;">High</span>
								<? } else if($percentage > 30) { ?>
									<? $maturity_level = 'MODERATE'; ?>
									<span style="color: #FFE65B;">Moderate</span>
								<? } else if($percentage > 10) { ?>
									<? $maturity_level = 'LOW'; ?>
									<span style="color: #CEF357;">Low</span>
								<? } else { ?>
									<? $maturity_level = 'VERY_LOW'; ?>
									<span style="color: #006600;">Very Low</span>
								<? } ?>
							</p>
						</div>
						<div class="col-xs-12 col-md-12 text-center">
							<a href="<?= url('wizard/inherentriskscore'); ?>" class="btn btn-primary">View Details</a>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
</div>

<script src="<?= url("3rdparty/echart/echarts-all.js"); ?>"></script>
<script src="<?= url("3rdparty/echart/green.js"); ?>"></script>
<script>
$(document).ready(function () {
	if($('#inherentRiskReportChart').length > 0){
		var maxScore = <?= $maxScore;?>;
		var totalScore = <?= $totalScore; ?>;

		var reportOptions = {
			animation: false,

			tooltip : {
				show: false
			},

			toolbox: {
				show : false
			},

			series : [
				{
					name:'the chart',
					type:'gauge',
					clickable: false,
					center : ['50%', '70%'],
					radius : [0, '100%'],
					startAngle: 180,
					endAngle: 0,
					min: 0,
					max: maxScore,
					splitNumber: maxScore,

					axisLine: {
						show: true,
						lineStyle: {
							color: [
								[0.1, '#7DDD4F'],
								[0.30, '#CEF357'],
								[0.70, '#FFE65B'],
								[0.9, '#FFA75B'],
								[1.00, '#FF5F5B']
							],
							width: 14
						}
					},

					axisTick: {
						show: true,
						splitNumber: 1,
						length :0,
					},

					axisLabel : {
						show: true,
						margin: 0,
						formatter: function(v){
							var low_label_position = Math.floor(maxScore * 0.1);
							var medium_label_position = Math.floor(maxScore * 0.5);
							var high_label_position = Math.floor(maxScore * 0.9);

							if(v == 0){
								return 0;
							}

							if(v == maxScore){
								return maxScore;
							}

							if((v % 200) == 0){
								return v;
							}

							/*switch (v){
								case low_label_position: return 'LOW';
								case medium_label_position: return 'MEDIUM';
								case high_label_position: return 'HIGH';
								default: return '';
							}*/
						},
						textStyle: {
							color: '#000',
							fontSize: 13,
							fontWeight: 'bold'
						}
					},

					splitLine: {
						show: false
					},

					pointer: {
						length : '80%',
						width : 8,
						color : 'auto'
					},

					title: {
						show : false,
					},

					detail: {
						show: true,
						offsetCenter: ['0%', '10%'],
						textStyle: {
							color: '#000',
							align: 'left',
							fontSize: 17
						},
						formatter: function(value){
							//return value + ' out of ' + maxScore + ' points';
						}
					},

					legendHoverLink: false,

					data:[
						{value: totalScore}
					]
				}
			]
		};

		var reportChart = echarts.init(document.getElementById('inherentRiskReportChart'), null);
		reportChart.setOption(reportOptions,true);
		$(window).on('resize', function(){
			reportChart.resize();
		});
	}

});
</script>

protected/views/wizard/vWizard.php
<?
/* @var $this WizardController */
/* @var $model CompanyInfo */
/* @var $form CActiveForm */

$labelClass = "control-label col-md-12 col-sm-12 col-xs-12";
$answerClass = "col-md-12 col-sm-12 col-xs-12";
$inputClass = "form-control col-md-12 col-sm-12 col-xs-12";
?>
<style type="text/css">
    .form-horizontal .control-label { text-align: left; padding-bottom: 5px;}
    .sep-radios { margin-right: 20px; }
    .form-section { width: auto; }
</style>
<div class="x_panel">
    <div class="x_title">
        <? $baselineName = Baseline_Ex::getCurrentBaselineName(); ?>
        <? if ($baselineName == 'Default') { ?>
            <h2>Security Setup Wizard</h2>
        <? } else { ?>
            <h2>Security Setup Wizard - <?= $baselineName; ?></h2>
        <? } ?>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <? $form=$this->beginWidget('CActiveForm', array('action'=>url('wizard/control',array('id'=>Obscure::encode($model->company_info_id))),
            'id'=>'company-info-form',
            'htmlOptions' => array('class'=>"form-horizontal form-label-left"),
            'enableAjaxValidation'=>false,
        )); ?>
        <div id="wizard" class="form_wizard wizard_horizontal">
            <ul class="wizard_steps">
                <li>
                    <a href="#step-1">
                        <span class="step_no">1</span>
                        <span class="step_descr">
                            <small style="display:none;"><small>Business Profile</small></small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-2">
                        <span class="step_no">2</span>
                        <span class="step_descr">
                            <small style="display:none;"><small>Target Security Posture</small></small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-3">
                        <span class="step_no">3</span>
                        <span class="step_descr">
                            <small style="display:none;"><small>Business Data Profile</small></small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-4">
                        <span class="step_no">4</span>
                        <span class="step_descr">
                            <small style="display:none;"><small>User Access to Information</small></small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#step-5">
                        <span class="step_no">5</span>
                        <span class="step_descr">
                            <small style="display:none;"><small>Information Technology Environment</small></small>
                        </span>
                    </a>
                </li>
            </ul>
            <? $params = array('model'=>$model,'form'=>$form,'labelClass'=>$labelClass,'answerClass'=>$answerClass,'inputClass'=>$inputClass,'showAllQuestions'=>$showAllQuestions); ?>
            <div id="step-1">
                <div class="form">
                    <?= $form->errorSummary($model); ?>
                </div>
                <? $this->renderPartial('_vStep1',$params); ?>
            </div>
            <div id="step-2">
                <? $this->renderPartial('_vStep2',$params); ?>
            </div>
            <div id="step-3">
                <? $this->renderPartial('_vStep3',$params); ?>
            </div>
            <div id="step-4">
                <? $this->renderPartial('_vStep4',$params); ?>
            </div>
            <div id="step-5">
                <? $this->renderPartial('_vStep5',$params); ?>
            </div>
        </div>
        <? $this->endWidget(); ?>
    </div>
</div>

<script type="text/javascript" src="<?= Yii::app()->request->baseUrl; ?>/3rdparty/wizard/jquery.smartWizard_v3_4.js"></script>
<script type="text/javascript">
    var __last_step = 0;
    $(function(){
        // Smart Wizard
        function onFinishCallback() {
            $('#company-info-form').submit();
        }
        function leaveAStepCallback(obj){
            __last_step= obj.attr('rel');
            //alert(__last_step);
            return true;
        }
        $('#wizard').smartWizard({
            hideButtonsOnDisabled:true,
            onLeaveStep:leaveAStepCallback,
            onFinish: onFinishCallback });
    });
</script>